#include "ui_strings.h"

static const UiHelpEntry UI_EN_HELP[] = {
	{"NAVIGATION", ""},
	{"  Tab / Shift+Tab", "Cycle through all VISIBLE panes"},
	{"  1-4 / ?", "Jump to specific Git view"},
	{"  \u2191/\u2193", "Move selection"},
	{"  \u2190/\u2192", "Switch focus (or Browser back/enter)"},
	{"  Home / End", "Top / bottom"},
	{"  PgUp/PgDn", "Page scroll"},
	{"", ""},
	{"CHANGES PANE", ""},
	{"  e", "Open selected file in Editor"},
	{"  Space / Ctrl+S", "Stage / unstage selected file"},
	{"  a / u", "Stage all / Unstage all"},
	{"  d", "Discard changes"},
	{"  Enter / =", "Toggle Diff pane"},
	{"", ""},
	{"EDITOR", ""},
	{"  e", "Toggle Editor visibility (right pane)"},
	{"  Arrows", "Move cursor"},
	{"  Enter", "Insert newline"},
	{"  BS", "Delete character"},
	{"  Ctrl+Z", "Undo"},
	{"  Ctrl+Y", "Redo"},
	{"  Ctrl+S", "Save file"},
	{"  Ctrl+X", "Cut selection"},
	{"  Ctrl+C / y", "Copy selection"},
	{"  Ctrl+V", "Paste from clipboard"},
	{"  Shift+Arrows", "Extend text selection"},
	{"", ""},
	{"FILE BROWSER", ""},
	{"  b", "Toggle Browser visibility (left pane)"},
	{"  \u2191/\u2193", "Move selection"},
	{"  Enter / \u2192", "Open file in Editor / Enter directory"},
	{"  \u2190", "Go back to parent directory"},
	{"", ""},
	{"DIFF SELECTION", ""},
	{"  Mouse Drag", "Select lines in diff view"},
	{"  Space / S", "Stage selected lines or hunk"},
	{"  U", "Unstage selected lines or hunk"},
	{"  y / Ctrl+C", "Copy selection to clipboard"},
	{"", ""},
	{"GLOBAL", ""},
	{"  c / Ctrl+C", "Commit staged changes"},
	{"  A", "Amend last commit"},
	{"  P / Ctrl+P", "Push to remote"},
	{"  f / Ctrl+F", "Fetch + pull"},
	{"  s", "Stash working changes"},
	{"  V", "Open in $VISUAL/$EDITOR"},
	{"  R / Ctrl+R / Ctrl+L", "Full refresh"},
	{"  T", "Cycle theme"},
	{"  ?", "Toggle this help"},
	{"  q / Esc / Ctrl+Q", "Go back / quit"},
	{"", ""},
	{"MOUSE", ""},
	{"  Click", "Focus pane, select item"},
	{"  Scroll wheel", "Scroll pane under cursor"},
	{NULL, NULL},
};

const UiStrings UI_EN = {
	.app_name = "tuide",
	.tabbar_title = " \u2387 tuide ",
	.exit_message = "tuide \u2014 bye!",
	.err_requires_terminal = "tuide: requires a terminal",
	.err_not_git_repo = "tuide: not a git repository",
	.err_failed_open_fmt = "tuide: failed to open %s",
	.branch_unknown = "(unknown)",

	.tab_changes = "Changes",
	.tab_log = "Log",
	.tab_branches = "Branches",
	.tab_stash = "Stash",
	.tab_help = "Help",

	.sidebar_browser_active = " \u25B6 BROWSER",
	.sidebar_browser_inactive = "   BROWSER",
	.sidebar_git_active = " \u25B6 GIT    ",
	.sidebar_git_inactive = "   GIT    ",

	.focus_unknown = " ??? ",
	.focus_changes = " CHANGES ",
	.focus_graph = " GRAPH   ",
	.focus_diff = " DIFF    ",
	.focus_browser = " BROWSER ",
	.focus_editor = " EDITOR  ",
	.focus_cli = " CLI     ",

	.hint_empty = "",
	.hint_status_changes =
		"c:commit  SPC:stage  a:all  u:unstage  d:discard  e:edit  V:editor  g/G:top/bot  "
		"W:wrap  "
		"T:theme",
	.hint_status_graph = "\u2191/\u2193:move  SPC/\u2192:expand  \u21B5:diff  g/G:top/bot  "
					"V:editor  W:wrap  T:theme",
	.hint_status_browser = "\u2191/\u2193:move  \u21B5/\u2192:open  \u2190:back  n:new  D:del  b:close",
	.hint_status_editor =
		"Arrows:move  Shift+Arrows:select  n/N:find  Ctrl+F:search  Ctrl+Z:undo  "
		"Ctrl+S:save  Ctrl+Q:quit  "
		"V:editor",
	.hint_status_diff = "\u2191/\u2193:scroll  g/G:top/bot  s:split  W:wrap  q:back  T:theme",
	.hint_log = "e:edit  \u2191/\u2193:move  \u21B5:diff  n:branch  s:side-by-side  T:theme",
	.hint_branches = "\u21B5:checkout  n:new  D:delete",
	.hint_stash = "\u21B5:apply  p:pop  D:drop  s:stash",
	.hint_editor_browser = "\u2191/\u2193:move  \u21B5/\u2192:open/enter  \u2190:back  Tab:editor",
	.hint_editor_editor =
		"Arrows:move  Shift:select  n/N:find next/prev  Ctrl+F:search  Ctrl+Z:undo  "
		"Ctrl+Y:redo  Ctrl+Q:quit  "
		"Ctrl+X:cut  Ctrl+C:copy  Ctrl+S:save",
	.hint_help = "q:close help",

	.menu_title = "Menu",
	.menu_copy = "Copy",
	.menu_cut = "Cut",
	.menu_paste = "Paste",
	.menu_cancel = "Cancel",
	.menu_stage = "Stage",
	.menu_unstage = "Unstage",
	.dialog_title = "Confirm",

	.prompt_find = "Find:",
	.prompt_go_to_line = "Go to line:",
	.prompt_go_to_file = "Go to File:",
	.prompt_global_search = "Global Search (grep):",
	.prompt_new_file = "New file name:",
	.prompt_commit_message = "Commit message:",
	.prompt_amend_message = "Amend message (empty=keep):",
	.prompt_stash_message = "Stash message (optional):",
	.prompt_new_branch = "New branch name:",

	.cli_prompt = " $ ",
	.msg_cli_executing_fmt = "Executing: %s",
	.msg_cli_success_fmt = "Success: %s",
	.msg_cli_failed_fmt = "Failed (%d): %s",
	.msg_cancelled = "Cancelled",

	.msg_nothing_to_undo = "Nothing to undo",
	.msg_undo = "Undo",
	.msg_nothing_to_redo = "Nothing to redo",
	.msg_redo = "Redo",
	.msg_saved_fmt = "Saved %s",
	.msg_jumped_to_line_fmt = "Jumped to line %d",
	.err_invalid_line_number = "Invalid line number",
	.msg_found_fmt = "Found: %s (n/N for next/prev)",
	.msg_found_wrapped_fmt = "Found (wrapped): %s",
	.err_not_found_fmt = "Not found: %s",
	.err_no_search_term = "No search term (Ctrl+F to search)",
	.msg_next_fmt = "Next: %s",
	.msg_next_wrapped_fmt = "Next (wrapped): %s",
	.msg_prev_fmt = "Prev: %s",
	.msg_prev_wrapped_fmt = "Prev (wrapped): %s",
	.msg_copied_editor_fmt = "Copied %d chars from editor to system clipboard",

	.msg_created_file_fmt = "Created %s",
	.err_failed_create_file_fmt = "Failed to create %s",
	.msg_deleted_file_fmt = "Deleted %s",
	.err_failed_delete_file_fmt = "Failed to delete %s",

	.msg_returned_from_fmt = "Returned from %s",
	.err_empty_commit_message = "Empty commit message",
	.err_nothing_staged = "Nothing staged",
	.msg_committed_fmt = "Committed: %.60s",
	.err_commit_failed = "Commit failed",
	.msg_amended = "Amended",
	.err_amend_failed = "Amend failed",
	.msg_theme_fmt = "Theme: %s",
	.msg_continuous_diff_fmt = "Continuous Diff: %s",
	.diff_continuous_on = "ON (full context)",
	.diff_continuous_off = "OFF (hunks only)",
	.msg_diff_wrap_fmt = "Diff wrap: %s",
	.msg_auto_watch_fmt = "Auto-watch: %s",
	.toggle_on = "ON",
	.toggle_off = "OFF",

	.msg_refreshed = "Refreshed",
	.msg_unstaged_fmt = "Unstaged: %s",
	.msg_staged_fmt = "Staged: %s",
	.msg_staged_all = "Staged all",
	.msg_unstaged_all = "Unstaged all",
	.err_select_working_tree_diff = "Select a working tree diff",
	.err_no_file_selected = "No file selected",
	.err_no_diff = "No diff",
	.err_viewing_unstaged_diff = "Viewing unstaged diff",
	.err_viewing_staged_diff = "Viewing staged diff",
	.err_parse_hunks = "Failed to parse hunks",
	.err_no_hunks = "No hunks to stage",
	.err_mkstemp_failed = "mkstemp failed",
	.err_mkstemp = "mkstemp",
	.err_out_of_memory = "Out of memory",
	.err_no_changed_lines_selected = "No changed lines selected",
	.err_no_hunk_selected = "No hunk selected",
	.msg_unstaged_selection = "Unstaged selection",
	.msg_staged_selection = "Staged selection",
	.err_unstage_failed = "Unstage failed",
	.err_stage_failed = "Stage failed",
	.msg_removed_fmt = "Removed: %s",
	.msg_discarded_fmt = "Discarded: %s",
	.err_empty_message = "Empty message",
	.msg_pushing = "Pushing...",
	.msg_pushed = "Pushed",
	.err_push_failed = "Push failed",
	.msg_pulling = "Pulling...",
	.msg_pulled = "Pulled",
	.err_pull_failed = "Pull failed",
	.msg_stashed = "Stashed",
	.err_stash_failed = "Stash failed",
	.msg_checked_out_fmt = "Checked out: %s",
	.err_checkout_failed = "Checkout failed",
	.err_name_required = "Name required",
	.msg_created_branch_fmt = "Created: %s",
	.err_branch_failed = "Branch failed",
	.err_cannot_delete_current_branch = "Cannot delete current branch",
	.msg_deleted_branch_fmt = "Deleted: %s",
	.err_delete_failed = "Delete failed",
	.msg_applied_stash_fmt = "Applied stash@{%d}",
	.err_apply_failed = "Apply failed",
	.msg_popped_stash_fmt = "Popped stash@{%d}",
	.err_pop_failed = "Pop failed",
	.msg_dropped_stash_fmt = "Dropped stash@{%d}",
	.err_drop_failed = "Drop failed",
	.msg_copied_clipboard_fmt = "Copied %d chars to system clipboard",
	.err_no_files_matching_fmt = "No files matching %s",
	.err_no_matches_fmt = "No matches for %s",

	.diff_title_empty = "Diff (select file or commit)",
	.diff_empty_msg = "(no diff \u2014 select a file or commit)",
	.diff_title_staged_suffix = " [staged]",
	.diff_title_files_fmt = "Files: %s",
	.diff_title_search_fmt = "Search: %s",
	.diff_title_commit_fmt = "commit %s: %s",
	.diff_title_files_prefix = "Files:",
	.diff_title_search_prefix = "Search:",
	.diff_title_commit_prefix = "commit ",
	.diff_view_full_label = "[View Full Diff]",
	.diff_label_old = " \u25C0 OLD",
	.diff_label_new = " NEW \u25B6 ",
	.diff_side_split = "Split",
	.diff_side_unify = "Unify",
	.diff_ctx_full = "Full",
	.diff_ctx_hunk = "Hunk",
	.diff_wrap_label_on = "Wrap",
	.diff_wrap_label_off = "NoWrap",

	.title_changes = "Changes",
	.title_graph = "Graph",
	.title_branches = "Branches",
	.title_commit_log = "Commit Log",
	.title_stash_fmt = "Stash (%d)",
	.title_help = "Help & Keybindings",
	.title_files = "Files",
	.title_editor = "Editor",
	.title_editor_save = " [Save] ",
	.editor_no_files = "(no files open)",
	.editor_status_position_fmt = " Ln %d, Col %d  ",
	.editor_status_encoding_lang_fmt = " [UTF-8]  %s ",
	.commit_placeholder = "commit message...",

	.header_commit_graph = "Graph",
	.header_commit_hash = "Hash",
	.header_commit_refs = "Refs",
	.header_commit_author = "Author",
	.header_commit_date = "Date",
	.header_commit_subject = "Subject",
	.header_branches_name = "Name",
	.header_branches_upstream = "Upstream",
	.header_branches_delta = "\u00B1",

	.header_staged_fmt = " \u2713 Staged (%d) ",
	.header_unstaged_fmt = " \u2717 Unstaged (%d) ",
	.commit_bar_icon = " \u270D ",
	.commit_button_label = " \u2713 Commit",
	.amend_button_label = " \u21BA Amend",

	.stash_empty_msg = "No stashes. Press 's' to stash changes.",

	.lang_plain_text = "Plain Text",
	.lang_c = "C",
	.lang_c_header = "C Header",
	.lang_cpp = "C++",
	.lang_python = "Python",
	.lang_javascript = "JavaScript",
	.lang_typescript = "TypeScript",
	.lang_markdown = "Markdown",

	.help_entries = UI_EN_HELP,
};

static const UiStrings *g_ui = &UI_EN;

const UiStrings *ui_strings(void) { return g_ui ? g_ui : &UI_EN; }

void ui_set_strings(const UiStrings *strings) { g_ui = strings ? strings : &UI_EN; }
